productpage:
  namespace: bank-bookinfo-uat
  image: ghcr.io/bankhubjar/bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-uat-productpage-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.dev.opsta.net
  # path: "/student108/productpage(/|$)(.*)"
  host: bookinfo.uat.hellodolphin.in.th
  path: "/bank/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  DETAILS_HOSTNAME: http://bookinfo-uat-details:8082/
  RATINGS_HOSTNAME: http://bookinfo-uat-ratings:8081/
  REVIEWS_HOSTNAME: http://bookinfo-uat-reviews:9080/
