productpage:
  namespace: bank-bookinfo-dev
  image: ghcr.io/bankhubjar/bookinfo-productpage
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-dev-productpage-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  # host: bookinfo.dev.opsta.net
  # path: "/student108/productpage(/|$)(.*)"
  host: bookinfo.dev.hellodolphin.in.th
  path: "/bank/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  DETAILS_HOSTNAME: http://details:8082/
  RATINGS_HOSTNAME: http://ratings:8081/
  REVIEWS_HOSTNAME: http://reviews:9080/